export interface Car {
  id: number;
  name: string;
  brand: string;
  type: string;
  category: string;
  year: number;
  price: number;
  threeDaySpecial: number;
  description: string;
  transmission: string;
  engine: string;
  topSpeed: string;
  images: string[];
  rating?: number;
  logo: string;
}

const cars: Car[] = [
  {
    id: 1,
    name: "Rolls-Royce Phantom",
    brand: "Rolls-Royce",
    type: "Sedan",
    category: "Luxury",
    year: 2023,
    price: 1500,
    threeDaySpecial: 4000,
    description: "The epitome of luxury motoring, featuring unparalleled comfort and sophistication.",
    transmission: "8-speed automatic",
    engine: "6.75L V12",
    topSpeed: "155 mph",
    images: [
      '/images/lamborghini/huracan-spyder/Lamborghini-Huracan-Spyder-front-600x400.jpg',
      '/images/lamborghini/huracan-spyder/Lamborghini-Huracan-Spyder-side-600x400.jpg',
      '/images/lamborghini/huracan-spyder/Lamborghini-Huracan-Spyder-rear-600x400.jpg',
      '/images/lamborghini/huracan-spyder/Lamborghini-Huracan-Spyder-interior-600x400.jpg',
      '/images/lamborghini/huracan-spyder/Lamborghini-Huracan-Spyder-top-down-600x400.jpg',
    ],
    category: 'convertible',
    description: `The Lamborghini Huracan Spyder offers the ultimate open-air driving experience. With a naturally aspirated 5.2-liter V10 engine producing 602 horsepower, the Huracan accelerates from 0-60 mph in 3.4 seconds. The car's soft-top roof can be opened or closed in just 17 seconds, even at speeds up to 30 mph. The interior features premium leather, a digital cockpit, and a high-definition touchscreen infotainment system, making this car both a technological and driving marvel.`,
  },
  {
    id: 14,
    name: 'Chevrolet Corvette',
    year: 2023,
    price: 999,
    images: [
      '/images/chevrolet/corvette/Chevrolet-Corvette-front-600x400.jpg',
      '/images/chevrolet/corvette/Chevrolet-Corvette-side-600x400.jpg',
      '/images/chevrolet/corvette/Chevrolet-Corvette-rear-600x400.jpg',
      '/images/chevrolet/corvette/Chevrolet-Corvette-interior-600x400.jpg',
      '/images/chevrolet/corvette/Chevrolet-Corvette-engine-600x400.jpg',
    ],
    category: 'sport',
    description: `The Chevrolet Corvette is a true American sports car icon. Powered by a 6.2-liter V8 engine with 495 horsepower, it goes from 0-60 mph in just 2.9 seconds. The Corvette features a mid-engine layout for perfect balance and handling. Inside, you'll find a driver-centric cockpit with premium materials, an 8-inch infotainment system, and performance data recorder. The car also comes with Michelin Pilot Sport 4S tires for track-ready performance.`,
  },
  {
    id: 15,
    name: 'Nissan GT-R',
    year: 2023,
    price: 899,
    images: [
      '/images/nissan/gt-r/Nissan-GT-R-front-600x400.jpg',
      '/images/nissan/gt-r/Nissan-GT-R-side-600x400.jpg',
      '/images/nissan/gt-r/Nissan-GT-R-rear-600x400.jpg',
      '/images/nissan/gt-r/Nissan-GT-R-interior-600x400.jpg',
      '/images/nissan/gt-r/Nissan-GT-R-engine-600x400.jpg',
    ],
    category: 'sport',
    description: `The Nissan GT-R, often called "Godzilla," is a performance beast with a 3.8-liter twin-turbo V6 producing 565 horsepower. This all-wheel-drive sports car reaches 0-60 mph in 2.9 seconds. The GT-R features cutting-edge technology, including the ATTESA E-TS all-wheel-drive system and a 6-speed dual-clutch transmission for precise gear shifts. The cabin features Recaro seats, a touchscreen navigation system, and a Bose audio system.`,
  },
  {
    id: 16,
    name: 'Ford Mustang GT',
    year: 2023,
    price: 799,
    images: [
      '/images/ford/mustang-gt/Ford-Mustang-GT-front-600x400.jpg',
      '/images/ford/mustang-gt/Ford-Mustang-GT-side-600x400.jpg',
      '/images/ford/mustang-gt/Ford-Mustang-GT-rear-600x400.jpg',
      '/images/ford/mustang-gt/Ford-Mustang-GT-interior-600x400.jpg',
      '/images/ford/mustang-gt/Ford-Mustang-GT-engine-600x400.jpg',
    ],
    category: 'sport',
    description: `The Ford Mustang GT is a muscle car legend. Its 5.0-liter V8 engine delivers 450 horsepower, allowing it to hit 0-60 mph in 4.0 seconds. The Mustang's aggressive exterior design features a vented hood, LED headlights, and quad exhausts. Inside, the Mustang offers premium materials, an 8-inch touchscreen with Ford's SYNC 3 system, and track apps for performance data.`,
  },
  {
    id: 17,
    name: 'Ford Mustang',
    year: 1965,
    price: 299,
    images: [
      '/images/ford/mustang-1965/Ford-Mustang-1965-front-600x400.jpg',
      '/images/ford/mustang-1965/Ford-Mustang-1965-side-600x400.jpg',
      '/images/ford/mustang-1965/Ford-Mustang-1965-rear-600x400.jpg',
      '/images/ford/mustang-1965/Ford-Mustang-1965-interior-600x400.jpg',
      '/images/ford/mustang-1965/Ford-Mustang-1965-engine-600x400.jpg',
    ],
    category: 'classic',
    description: `The 1965 Ford Mustang is an American classic and one of the most iconic cars ever made. It comes with a 289 cubic inch V8 engine producing 271 horsepower and is mated to a 4-speed manual transmission. The Mustang can go from 0-60 mph in around 6.5 seconds. With its vintage design, chrome accents, and muscle car sound, this is a must-drive for car enthusiasts. Inside, you'll find a retro dashboard with analog gauges, vinyl bucket seats, and an AM/FM radio. The Mustang represents the pinnacle of the classic American muscle car era.`,
  },
  {
    id: 18,
    name: 'Chevrolet Camaro',
    year: 1969,
    price: 399,
    images: [
      '/images/chevrolet/camaro-1969/Chevrolet-Camaro-1969-front-600x400.jpg',
      '/images/chevrolet/camaro-1969/Chevrolet-Camaro-1969-side-600x400.jpg',
      '/images/chevrolet/camaro-1969/Chevrolet-Camaro-1969-rear-600x400.jpg',
      '/images/chevrolet/camaro-1969/Chevrolet-Camaro-1969-interior-600x400.jpg',
      '/images/chevrolet/camaro-1969/Chevrolet-Camaro-1969-engine-600x400.jpg',
    ],
    category: 'classic',
    description: `The 1969 Chevrolet Camaro is one of the most sought-after muscle cars of its era. It is powered by a 396 cubic inch V8 engine that generates 375 horsepower, allowing the Camaro to reach 0-60 mph in about 5.5 seconds. Its aggressive stance, bold styling, and iconic front grille make it a head-turner wherever it goes. Inside, the Camaro features black vinyl upholstery, woodgrain trim, and a 4-speed manual transmission. This car is a true piece of American muscle car history.`,
  },
  {
    id: 19,
    name: 'Dodge Charger',
    year: 1970,
    price: 349,
    images: [
      '/images/dodge/charger-1970/Dodge-Charger-1970-front-600x400.jpg',
      '/images/dodge/charger-1970/Dodge-Charger-1970-side-600x400.jpg',
      '/images/dodge/charger-1970/Dodge-Charger-1970-rear-600x400.jpg',
      '/images/dodge/charger-1970/Dodge-Charger-1970-interior-600x400.jpg',
      '/images/dodge/charger-1970/Dodge-Charger-1970-engine-600x400.jpg',
    ],
    category: 'classic',
    description: `The 1970 Dodge Charger is one of the most iconic muscle cars ever produced. Under the hood is a 440 cubic inch V8 engine producing 390 horsepower, which rockets the Charger from 0-60 mph in just over 5.5 seconds. The Charger's unmistakable fastback design, hideaway headlights, and signature "Coke bottle" curves make it a legend in automotive design. The interior offers vinyl bucket seats, a wood-rimmed steering wheel, and a pistol grip shifter, adding to the car's retro charm.`,
  },
  {
    id: 20,
    name: 'Tesla Model S',
    year: 2023,
    price: 599,
    images: [
      '/images/tesla/model-s/Tesla-Model-S-front-600x400.jpg',
      '/images/tesla/model-s/Tesla-Model-S-side-600x400.jpg',
      '/images/tesla/model-s/Tesla-Model-S-rear-600x400.jpg',
      '/images/tesla/model-s/Tesla-Model-S-interior-600x400.jpg',
      '/images/tesla/model-s/Tesla-Model-S-dashboard-600x400.jpg',
    ],
    category: 'sedan',
    description: `The Tesla Model S is the ultimate electric luxury sedan, combining cutting-edge technology and performance. The dual-motor all-wheel-drive system produces 670 horsepower, allowing the Model S to reach 0-60 mph in 3.1 seconds. With a top speed of 155 mph and an impressive range of over 400 miles per charge, this is one of the most advanced electric vehicles on the market. Inside, the Model S features a 17-inch touchscreen display, full self-driving capabilities, and vegan leather seating.`,
  },
  {
    id: 21,
    name: 'Audi R8',
    year: 2023,
    price: 1499,
    images: [
      '/images/audi/r8/Audi-R8-front-600x400.jpg',
      '/images/audi/r8/Audi-R8-side-600x400.jpg',
      '/images/audi/r8/Audi-R8-rear-600x400.jpg',
      '/images/audi/r8/Audi-R8-interior-600x400.jpg',
      '/images/audi/r8/Audi-R8-engine-600x400.jpg',
    ],
    category: 'super',
    description: `The Audi R8 is a stunning mid-engine supercar with a 5.2-liter V10 engine producing 602 horsepower. The R8's Quattro all-wheel-drive system helps it reach 0-60 mph in just 3.2 seconds, with a top speed of 205 mph. Inside, the R8 offers a driver-focused cockpit with leather and Alcantara surfaces, a 12.3-inch digital instrument cluster, and premium Bang & Olufsen sound. The R8 is a supercar that's as comfortable on the highway as it is on the track.`,
  },
  {
    id: 22,
    name: 'Porsche Panamera',
    year: 2023,
    price: 1299,
    images: [
      '/images/porsche/panamera/Porsche-Panamera-front-600x400.jpg',
      '/images/porsche/panamera/Porsche-Panamera-side-600x400.jpg',
      '/images/porsche/panamera/Porsche-Panamera-rear-600x400.jpg',
      '/images/porsche/panamera/Porsche-Panamera-interior-600x400.jpg',
      '/images/porsche/panamera/Porsche-Panamera-dashboard-600x400.jpg',
    ],
    category: 'sedan',
    description: `The Porsche Panamera offers the performance of a sports car with the comfort and luxury of a sedan. Powered by a twin-turbocharged 4.0-liter V8 engine, the Panamera produces 620 horsepower and hits 0-60 mph in just 3.1 seconds. The cabin features premium leather, a Burmester surround sound system, and Porsche's advanced infotainment system with a 12.3-inch touchscreen. With a top speed of 196 mph, the Panamera delivers a unique blend of practicality and exhilarating performance.`,
  },
  {
    id: 23,
    name: 'Jaguar F-Type',
    year: 2023,
    price: 1499,
    images: [
      '/images/jaguar/f-type/Jaguar-F-Type-front-600x400.jpg',
      '/images/jaguar/f-type/Jaguar-F-Type-side-600x400.jpg',
      '/images/jaguar/f-type/Jaguar-F-Type-rear-600x400.jpg',
      '/images/jaguar/f-type/Jaguar-F-Type-interior-600x400.jpg',
      '/images/jaguar/f-type/Jaguar-F-Type-engine-600x400.jpg',
    ],
    category: 'sport',
    description: `The Jaguar F-Type is a stunning performance coupe, with a supercharged 5.0-liter V8 engine producing 575 horsepower. The F-Type's active exhaust system and aggressive styling give it a unique presence on the road. With a top speed of 186 mph and 0-60 mph in just 3.5 seconds, the F-Type delivers thrilling acceleration. Inside, you'll find premium leather seats, a 10-inch touchscreen, and a Meridian sound system.`,
  },
  {
    id: 24,
    name: 'Chevrolet Impala',
    year: 1967,
    price: 249,
    images: [
      '/images/chevrolet/impala-1967/Chevrolet-Impala-1967-front-600x400.jpg',
      '/images/chevrolet/impala-1967/Chevrolet-Impala-1967-side-600x400.jpg',
      '/images/chevrolet/impala-1967/Chevrolet-Impala-1967-rear-600x400.jpg',
      '/images/chevrolet/impala-1967/Chevrolet-Impala-1967-interior-600x400.jpg',
      '/images/chevrolet/impala-1967/Chevrolet-Impala-1967-engine-600x400.jpg',
    ],
    category: 'classic',
    description: `The 1967 Chevrolet Impala is a full-sized American classic known for its sleek design and powerful V8 engine. Powered by a 427 cubic inch big-block engine producing 385 horsepower, this car can sprint from 0-60 mph in just over 7 seconds. The Impala features a long, low body with smooth lines, chrome accents, and iconic round taillights. Inside, it offers spacious bench seating, a simple yet elegant dashboard, and a four-speed manual transmission. It's a classic cruiser that blends performance and comfort perfectly.`,
  },
  {
    id: 25,
    name: 'Aston Martin DB11',
    year: 2023,
    price: 1599,
    images: [
      '/images/aston-martin/db11/Aston-Martin-DB11-front-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-side-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-rear-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-interior-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-engine-600x400.jpg',
    ],
    category: 'luxury',
    description: `The Aston Martin DB11 is a grand tourer that blends luxury, performance, and style. It is powered by a twin-turbo 5.2-liter V12 engine producing 630 horsepower, capable of accelerating from 0-60 mph in 3.7 seconds, with a top speed of 208 mph. The DB11 features a lightweight aluminum body, aggressive yet elegant styling, and advanced aerodynamics. Inside, you'll find handcrafted leather seats, an 8-inch infotainment system, and a Bang & Olufsen audio system, making the DB11 an exquisite blend of luxury and performance.`,
  },
  {
    id: 26,
    name: 'Maserati Ghibli',
    year: 2023,
    price: 899,
    images: [
      '/images/maserati/ghibli/Maserati-Ghibli-front-600x400.jpg',
      '/images/maserati/ghibli/Maserati-Ghibli-side-600x400.jpg',
      '/images/maserati/ghibli/Maserati-Ghibli-rear-600x400.jpg',
      '/images/maserati/ghibli/Maserati-Ghibli-interior-600x400.jpg',
      '/images/maserati/ghibli/Maserati-Ghibli-dashboard-600x400.jpg',
    ],
    category: 'sedan',
    description: `The Maserati Ghibli is a luxury sedan with the soul of a sports car. It is powered by a 3.8-liter twin-turbo V8 engine that generates 580 horsepower, propelling the Ghibli from 0-60 mph in just 4.0 seconds. The sleek, Italian styling is complemented by premium leather upholstery, an 8.4-inch touchscreen infotainment system, and a 15-speaker Bowers & Wilkins audio system. With a top speed of 178 mph, the Ghibli offers the perfect combination of style, speed, and luxury.`,
  },
  {
    id: 27,
    name: 'Lexus LS',
    year: 2023,
    price: 799,
    images: [
      '/images/lexus/ls/Lexus-LS-front-600x400.jpg',
      '/images/lexus/ls/Lexus-LS-side-600x400.jpg',
      '/images/lexus/ls/Lexus-LS-rear-600x400.jpg',
      '/images/lexus/ls/Lexus-LS-interior-600x400.jpg',
      '/images/lexus/ls/Lexus-LS-dashboard-600x400.jpg',
    ],
    category: 'sedan',
    description: `The Lexus LS is the epitome of luxury, featuring a hybrid powertrain that pairs a 3.5-liter V6 engine with electric motors to deliver 354 horsepower. The LS is capable of reaching 0-60 mph in 5.1 seconds while providing exceptional fuel efficiency. The interior boasts semi-aniline leather seating, wood trim, and a 12.3-inch multimedia display with Apple CarPlay and Android Auto. The Lexus LS offers a refined driving experience with an emphasis on comfort and cutting-edge technology.`,
  },
  {
    id: 28,
    name: 'Dodge Viper',
    year: 2023,
    price: 1199,
    images: [
      '/images/dodge/viper/Dodge-Viper-front-600x400.jpg',
      '/images/dodge/viper/Dodge-Viper-side-600x400.jpg',
      '/images/dodge/viper/Dodge-Viper-rear-600x400.jpg',
      '/images/dodge/viper/Dodge-Viper-interior-600x400.jpg',
      '/images/dodge/viper/Dodge-Viper-engine-600x400.jpg',
    ],
    category: 'sport',
    description: `The Dodge Viper is a pure American muscle car, boasting an 8.4-liter V10 engine that produces 645 horsepower and 600 lb-ft of torque. It accelerates from 0-60 mph in just 3.5 seconds, with a top speed of 206 mph. The Viper's aggressive styling is matched by its raw power, while the interior features race-inspired bucket seats, a 7-inch digital instrument cluster, and a high-performance Harman Kardon audio system. The Viper is designed for those who crave speed and adrenaline.`,
  },
  {
    id: 29,
    name: 'Jeep Grand Cherokee',
    year: 2023,
    price: 599,
    images: [
      '/images/jeep/grand-cherokee/Jeep-Grand-Cherokee-front-600x400.jpg',
      '/images/jeep/grand-cherokee/Jeep-Grand-Cherokee-side-600x400.jpg',
      '/images/jeep/grand-cherokee/Jeep-Grand-Cherokee-rear-600x400.jpg',
      '/images/jeep/grand-cherokee/Jeep-Grand-Cherokee-interior-600x400.jpg',
      '/images/jeep/grand-cherokee/Jeep-Grand-Cherokee-offroad-600x400.jpg',
    ],
    category: 'SUVs',
    description: `The Jeep Grand Cherokee is a midsize SUV that combines rugged off-road capability with luxurious amenities. Powered by a 3.6-liter V6 engine delivering 293 horsepower, it's equipped with advanced 4x4 systems for any terrain. The Grand Cherokee's interior includes leather-trimmed seating, an 8.4-inch touchscreen infotainment system with navigation, and a 9-speaker audio system. Whether navigating city streets or rough trails, the Grand Cherokee is built for adventure.`,
  },
  {
    id: 30,
    name: 'Tesla Model X',
    year: 2023,
    price: 799,
    images: [
      '/images/tesla/model-x/Tesla-Model-X-front-600x400.jpg',
      '/images/tesla/model-x/Tesla-Model-X-side-600x400.jpg',
      '/images/tesla/model-x/Tesla-Model-X-rear-600x400.jpg',
      '/images/tesla/model-x/Tesla-Model-X-interior-600x400.jpg',
      '/images/tesla/model-x/Tesla-Model-X-falcon-doors-600x400.jpg',
    ],
    category: 'SUVs',
    description: `The Tesla Model X is an all-electric luxury SUV with futuristic Falcon Wing doors and an impressive range of up to 360 miles. It is powered by dual electric motors that produce up to 1,020 horsepower in the Plaid version, allowing the Model X to reach 0-60 mph in just 2.5 seconds. The Model X also features a panoramic windshield, a 17-inch touchscreen, and the Autopilot suite for semi-autonomous driving. With seating for seven and a cutting-edge design, the Model X offers both luxury and sustainability.`,
  },
  {
    id: 31,
    name: 'Mercedes-Benz GLC',
    year: 2023,
    price: 749,
    images: [
      '/images/mercedes-benz/glc/Mercedes-Benz-GLC-front-600x400.jpg',
      '/images/mercedes-benz/glc/Mercedes-Benz-GLC-side-600x400.jpg',
      '/images/mercedes-benz/glc/Mercedes-Benz-GLC-rear-600x400.jpg',
      '/images/mercedes-benz/glc/Mercedes-Benz-GLC-interior-600x400.jpg',
      '/images/mercedes-benz/glc/Mercedes-Benz-GLC-dashboard-600x400.jpg',
    ],
    category: 'SUVs',
    description: `The Mercedes-Benz GLC is a compact luxury SUV that delivers elegance and performance. Powered by a 2.0-liter turbocharged four-cylinder engine producing 255 horsepower, the GLC offers a smooth and dynamic driving experience. It features a high-tech interior with a 10.25-inch touchscreen infotainment system, premium materials, and advanced safety features. The GLC's 4MATIC all-wheel-drive system ensures stability in various driving conditions, making it a versatile choice for both city streets and rough terrain.`,
  },
  {
    id: 32,
    name: 'Ford Explorer',
    year: 2023,
    price: 599,
    images: [
      '/images/ford/explorer/Ford-Explorer-front-600x400.jpg',
      '/images/ford/explorer/Ford-Explorer-side-600x400.jpg',
      '/images/ford/explorer/Ford-Explorer-rear-600x400.jpg',
      '/images/ford/explorer/Ford-Explorer-interior-600x400.jpg',
      '/images/ford/explorer/Ford-Explorer-third-row-600x400.jpg',
    ],
    category: 'SUVs',
    description: `The 2023 Ford Explorer is a versatile mid-size SUV that combines rugged capability with modern comforts. Powered by a 2.3-liter EcoBoost engine delivering 300 horsepower, the Explorer offers both power and fuel efficiency. Inside, you'll find a spacious cabin with a 12.3-inch digital display, Ford's SYNC 4 infotainment system, and seating for up to seven passengers. Its all-wheel-drive system ensures that the Explorer is ready for any adventure, making it perfect for family trips and off-road excursions.`,
  },
  {
    id: 33,
    name: 'Chevrolet Tahoe',
    year: 2023,
    price: 699,
    images: [
      '/images/chevrolet/tahoe/Chevrolet-Tahoe-front-600x400.jpg',
      '/images/chevrolet/tahoe/Chevrolet-Tahoe-side-600x400.jpg',
      '/images/chevrolet/tahoe/Chevrolet-Tahoe-rear-600x400.jpg',
      '/images/chevrolet/tahoe/Chevrolet-Tahoe-interior-600x400.jpg',
      '/images/chevrolet/tahoe/Chevrolet-Tahoe-cargo-600x400.jpg',
    ],
    category: 'SUVs',
    description: `The 2023 Chevrolet Tahoe is a full-size SUV built for those who demand space, power, and utility. Equipped with a 5.3-liter V8 engine generating 355 horsepower, the Tahoe is capable of towing up to 8,400 pounds. Inside, you'll find a luxurious and spacious cabin with seating for up to nine passengers, a 10.2-inch touchscreen infotainment system, and a premium audio system. The Tahoe's powerful performance and robust frame make it ideal for both family travel and heavy-duty tasks.`,
  },
  {
    id: 34,
    name: 'Bentley Bentayga',
    year: 2023,
    price: 1699,
    images: [
      '/images/bentley/bentayga/Bentley-Bentayga-front-600x400.jpg',
      '/images/bentley/bentayga/Bentley-Bentayga-side-600x400.jpg',
      '/images/bentley/bentayga/Bentley-Bentayga-rear-600x400.jpg',
      '/images/bentley/bentayga/Bentley-Bentayga-interior-600x400.jpg',
      '/images/bentley/bentayga/Bentley-Bentayga-dashboard-600x400.jpg',
    ],
    category: 'luxury',
    description: `The Bentley Bentayga is a luxury SUV that combines the craftsmanship and opulence of Bentley with SUV practicality. Under the hood is a 4.0-liter V8 engine producing 542 horsepower, propelling the Bentayga from 0-60 mph in 4.4 seconds. The Bentayga offers an exquisitely appointed cabin with hand-stitched leather seats, a panoramic roof, and a high-resolution 10.9-inch touchscreen. Designed for both city streets and rugged terrain, the Bentayga offers a perfect blend of performance and luxury.`,
  },
  {
    id: 35,
    name: 'Lamborghini Urus',
    year: 2023,
    price: 1999,
    images: [
      '/images/lamborghini/urus/Lamborghini-Urus-front-600x400.jpg',
      '/images/lamborghini/urus/Lamborghini-Urus-side-600x400.jpg',
      '/images/lamborghini/urus/Lamborghini-Urus-rear-600x400.jpg',
      '/images/lamborghini/urus/Lamborghini-Urus-interior-600x400.jpg',
      '/images/lamborghini/urus/Lamborghini-Urus-dashboard-600x400.jpg',
    ],
    category: 'super',
    description: `The Lamborghini Urus is the world's first super SUV, combining the high-performance DNA of Lamborghini with the practicality of an SUV. Powered by a 4.0-liter twin-turbo V8 engine producing 641 horsepower, the Urus can accelerate from 0-60 mph in just 3.5 seconds. The interior boasts a luxurious blend of fine leather, carbon fiber, and Alcantara, along with Lamborghini's cutting-edge technology and infotainment systems. It's the ultimate fusion of speed, style, and utility.`,
  },
  {
    id: 36,
    name: 'Bugatti Chiron',
    year: 2023,
    price: 2999,
    images: [
      '/images/bugatti/chiron/Bugatti-Chiron-front-600x400.jpg',
      '/images/bugatti/chiron/Bugatti-Chiron-side-600x400.jpg',
      '/images/bugatti/chiron/Bugatti-Chiron-rear-600x400.jpg',
      '/images/bugatti/chiron/Bugatti-Chiron-interior-600x400.jpg',
      '/images/bugatti/chiron/Bugatti-Chiron-engine-600x400.jpg',
    ],
    category: 'super',description: `The Bugatti Chiron is a masterpiece of automotive engineering and the pinnacle of hypercar performance. With an 8.0-liter quad-turbocharged W16 engine producing 1,479 horsepower, the Chiron reaches speeds of over 261 mph. Inside, the cabin is a blend of exquisite materials, advanced technology, and ultimate comfort. Every detail is meticulously crafted, making the Chiron the ultimate symbol of luxury, speed, and exclusivity.`,
},
{
  id: 37,
  name: 'Jaguar E-Type',
  year: 1971,
  price: 599,
  images: [
    '/images/jaguar/e-type-1971/Jaguar-E-Type-1971-front-600x400.jpg',
    '/images/jaguar/e-type-1971/Jaguar-E-Type-1971-side-600x400.jpg',
    '/images/jaguar/e-type-1971/Jaguar-E-Type-1971-rear-600x400.jpg',
    '/images/jaguar/e-type-1971/Jaguar-E-Type-1971-interior-600x400.jpg',
    '/images/jaguar/e-type-1971/Jaguar-E-Type-1971-engine-600x400.jpg',
  ],
  category: 'classic',
  description: `The Jaguar E-Type, also known as the XK-E in the United States, is a British sports car icon that has been praised for its beauty and performance since its release. This 1971 model is powered by a 5.3-liter V12 engine, producing 265 horsepower, and is capable of reaching a top speed of 150 mph. The E-Type's sleek bodywork and timeless design have made it a favorite among car enthusiasts for decades. This classic beauty is perfect for those looking to relive the golden age of motoring.`,
},
{
  id: 38,
  name: 'McLaren 720S',
  year: 2023,
  price: 2999,
  images: [
    '/images/mclaren/720s/McLaren-720S-front-600x400.jpg',
    '/images/mclaren/720s/McLaren-720S-side-600x400.jpg',
    '/images/mclaren/720s/McLaren-720S-rear-600x400.jpg',
    '/images/mclaren/720s/McLaren-720S-interior-600x400.jpg',
    '/images/mclaren/720s/McLaren-720S-engine-600x400.jpg',
  ],
  category: 'super',
  description: `The McLaren 720S is a stunning supercar that redefines performance and agility. Powered by a 4.0-liter twin-turbo V8 engine producing 710 horsepower, the 720S can hit 0-60 mph in a blistering 2.7 seconds, with a top speed of 212 mph. Its aerodynamic design, lightweight carbon fiber body, and active suspension system ensure optimal handling and speed. Inside, the driver-focused cabin features luxury materials, advanced technology, and a minimalist design, providing a thrilling yet comfortable driving experience.`,
},
{
  id: 39,
  name: 'Ferrari LaFerrari',
  year: 2023,
  price: 3999,
  images: [
    '/images/ferrari/laferrari/Ferrari-LaFerrari-front-600x400.jpg',
    '/images/ferrari/laferrari/Ferrari-LaFerrari-side-600x400.jpg',
    '/images/ferrari/laferrari/Ferrari-LaFerrari-rear-600x400.jpg',
    '/images/ferrari/laferrari/Ferrari-LaFerrari-interior-600x400.jpg',
    '/images/ferrari/laferrari/Ferrari-LaFerrari-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Ferrari LaFerrari is a hybrid hypercar that embodies the pinnacle of Ferrari's engineering and design expertise. With a combined power output of 950 horsepower from its 6.3-liter V12 engine and electric motor, the LaFerrari reaches 0-60 mph in under 3 seconds and tops out at 217 mph. The exterior is sculpted for maximum aerodynamic efficiency, while the interior is a mix of luxurious materials and cutting-edge technology, making every drive an unforgettable experience.`,
},
{
  id: 40,
  name: 'Pagani Huayra',
  year: 2023,
  price: 5999,
  images: [
    '/images/pagani/huayra/Pagani-Huayra-front-600x400.jpg',
    '/images/pagani/huayra/Pagani-Huayra-side-600x400.jpg',
    '/images/pagani/huayra/Pagani-Huayra-rear-600x400.jpg',
    '/images/pagani/huayra/Pagani-Huayra-interior-600x400.jpg',
    '/images/pagani/huayra/Pagani-Huayra-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Pagani Huayra is an exotic hypercar that combines elegance and performance in equal measure. Its 6.0-liter twin-turbocharged V12 engine, producing 720 horsepower, enables the Huayra to accelerate from 0-60 mph in 2.8 seconds and achieve a top speed of 230 mph. Handcrafted with extreme attention to detail, the Huayra's interior is adorned with luxurious materials such as leather, carbon fiber, and titanium, creating an atmosphere of both sophistication and cutting-edge technology.`,
},
{
  id: 41,
  name: 'Koenigsegg Agera RS',
  year: 2023,
  price: 6999,
  images: [
    '/images/koenigsegg/agera-rs/Koenigsegg-Agera-RS-front-600x400.jpg',
    '/images/koenigsegg/agera-rs/Koenigsegg-Agera-RS-side-600x400.jpg',
    '/images/koenigsegg/agera-rs/Koenigsegg-Agera-RS-rear-600x400.jpg',
    '/images/koenigsegg/agera-rs/Koenigsegg-Agera-RS-interior-600x400.jpg',
    '/images/koenigsegg/agera-rs/Koenigsegg-Agera-RS-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Koenigsegg Agera RS is one of the fastest and most technologically advanced hypercars ever made. Powered by a 5.0-liter twin-turbo V8 engine that generates 1,160 horsepower, the Agera RS can accelerate from 0-60 mph in 2.6 seconds, with a top speed of over 275 mph. The Agera RS holds the world record for the fastest production car, showcasing Koenigsegg's commitment to pushing the boundaries of automotive engineering.`,
},
{
  id: 42,
  name: 'Aston Martin Valkyrie',
  year: 2023,
  price: 4599,
  images: [
    '/images/aston-martin/valkyrie/Aston-Martin-Valkyrie-front-600x400.jpg',
    '/images/aston-martin/valkyrie/Aston-Martin-Valkyrie-side-600x400.jpg',
    '/images/aston-martin/valkyrie/Aston-Martin-Valkyrie-rear-600x400.jpg',
    '/images/aston-martin/valkyrie/Aston-Martin-Valkyrie-interior-600x400.jpg',
    '/images/aston-martin/valkyrie/Aston-Martin-Valkyrie-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Aston Martin Valkyrie is a track-focused hypercar that brings Formula 1-level technology to the road. Developed in collaboration with Red Bull Racing, the Valkyrie is powered by a 6.5-liter naturally aspirated V12 engine paired with an electric motor, producing a combined 1,160 horsepower. The car's lightweight carbon fiber body, extreme aerodynamics, and race-derived technology make the Valkyrie one of the most thrilling and exclusive cars available today.`,
},
{
  id: 43,
  name: 'Lamborghini Veneno',
  year: 2023,
  price: 4999,
  images: [
    '/images/lamborghini/veneno/Lamborghini-Veneno-front-600x400.jpg',
    '/images/lamborghini/veneno/Lamborghini-Veneno-side-600x400.jpg',
    '/images/lamborghini/veneno/Lamborghini-Veneno-rear-600x400.jpg',
    '/images/lamborghini/veneno/Lamborghini-Veneno-interior-600x400.jpg',
    '/images/lamborghini/veneno/Lamborghini-Veneno-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Lamborghini Veneno is one of the most extreme hypercars ever created by Lamborghini. Its 6.5-liter V12 engine produces 740 horsepower, enabling the Veneno to accelerate from 0-60 mph in just 2.8 seconds, with a top speed of 221 mph. The aggressive design, with its sharp lines and massive rear wing, reflects Lamborghini's commitment to performance and aerodynamic efficiency. Only a few Venenos were ever made, making it one of the rarest and most sought-after hypercars in the world.`,
},
{
  id: 44,
  name: 'Ferrari FXX K',
  year: 2023,
  price: 4599,
  images: [
    '/images/ferrari/fxx-k/Ferrari-FXX-K-front-600x400.jpg',
    '/images/ferrari/fxx-k/Ferrari-FXX-K-side-600x400.jpg',
    '/images/ferrari/fxx-k/Ferrari-FXX-K-rear-600x400.jpg',
    '/images/ferrari/fxx-k/Ferrari-FXX-K-interior-600x400.jpg',
    '/images/ferrari/fxx-k/Ferrari-FXX-K-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Ferrari FXX K is a limited-edition, track-only hypercar based on the LaFerrari. With its 6.3-liter V12 engine and electric motor producing over 1,036 horsepower, the FXX K can reach speeds of over 217 mph. Designed exclusively for racing, the FXX K features advanced aerodynamics, lightweight materials, and cutting-edge technology. It is one of the most exclusive and high-performance Ferraris ever made.`,
},
{
  id: 45,
  name: 'Porsche 918 Spyder',
  year: 2023,
  price: 3500,
  images: [
    '/images/porsche/918-spyder/Porsche-918-Spyder-front-600x400.jpg',
    '/images/porsche/918-spyder/Porsche-918-Spyder-side-600x400.jpg',
    '/images/porsche/918-spyder/Porsche-918-Spyder-rear-600x400.jpg',
    '/images/porsche/918-spyder/Porsche-918-Spyder-interior-600x400.jpg',
    '/images/porsche/918-spyder/Porsche-918-Spyder-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Porsche 918 Spyder is a hybrid hypercar that combines a 4.6-liter V8 engine with two electric motors, generating a total of 887 horsepower. With a 0-60 mph time of 2.5 seconds and a top speed of 214 mph, the 918 Spyder offers both stunning performance and remarkable efficiency. The car's carbon fiber body and advanced aerodynamics, combined with Porsche's legendary engineering, make the 918 Spyder a true masterpiece of automotive innovation.`,
},
{
  id: 46,
  name: 'Maserati MC12',
  year: 2023,
  price: 3999,
  images: [
    '/images/maserati/mc12/Maserati-MC12-front-600x400.jpg',
    '/images/maserati/mc12/Maserati-MC12-side-600x400.jpg',
    '/images/maserati/mc12/Maserati-MC12-rear-600x400.jpg',
    '/images/maserati/mc12/Maserati-MC12-interior-600x400.jpg',
    '/images/maserati/mc12/Maserati-MC12-engine-600x400.jpg',
  ],
  category: 'exotic',
  description: `The Maserati MC12 is a rare and exclusive supercar built to dominate the racetrack. Powered by a 6.0-liter V12 engine that produces 621 horsepower, the MC12 accelerates from 0-60 mph in 3.8 seconds and has a top speed of 205 mph. Its unique design and limited production numbers make it one of the most coveted supercars in the world. The MC12's track pedigree and luxurious interior offer the perfect balance of high performance and refined elegance.`,
},
{
  id: 47,
  name: 'Jaguar F-Type SVR',
  year: 2023,
  price: 1799,
  images: [
    '/images/jaguar/f-type-svr/Jaguar-F-Type-SVR-front-600x400.jpg',
    '/images/jaguar/f-type-svr/Jaguar-F-Type-SVR-side-600x400.jpg',
    '/images/jaguar/f-type-svr/Jaguar-F-Type-SVR-rear-600x400.jpg',
    '/images/jaguar/f-type-svr/Jaguar-F-Type-SVR-interior-600x400.jpg',
    '/images/jaguar/f-type-svr/Jaguar-F-Type-SVR-engine-600x400.jpg',
  ],
  category: 'sport',
  description: `The Jaguar F-Type SVR is the ultimate expression of Jaguar's sports car prowess. Powered by a 5.0-liter supercharged V8 engine that delivers 575 horsepower, the F-Type SVR can sprint from 0-60 mph in just 3.5 seconds and reach a top speed of 200 mph. With its sleek design, responsive handling, and luxurious interior, the F-Type SVR is a true driver's car that offers both thrilling performance and everyday comfort.`,
},
{
  id: 48,
  name: 'Mercedes-AMG GT R',
  year: 2023,
  price: 2099,
  images: [
    '/images/mercedes-amg/gt-r/Mercedes-AMG-GT-R-front-600x400.jpg',
    '/images/mercedes-amg/gt-r/Mercedes-AMG-GT-R-side-600x400.jpg',
    '/images/mercedes-amg/gt-r/Mercedes-AMG-GT-R-rear-600x400.jpg',
    '/images/mercedes-amg/gt-r/Mercedes-AMG-GT-R-interior-600x400.jpg',
    '/images/mercedes-amg/gt-r/Mercedes-AMG-GT-R-engine-600x400.jpg',
    ],
    category: 'sport',
    description: `The Mercedes-AMG GT R is a track-focused beast that offers unparalleled performance and handling. With its 4.0-liter twin-turbo V8 engine producing 577 horsepower, the GT R accelerates from 0-60 mph in 3.5 seconds and reaches a top speed of 198 mph. The aggressive styling, active aerodynamics, and advanced suspension system make the GT R a formidable machine both on the road and the racetrack. Its luxurious cabin ensures that drivers enjoy comfort and style while pushing the car to its limits.`,
  },
  {
    id: 49,
    name: 'Lamborghini Huracan Evo',
    year: 2023,
    price: 2499,
    images: [
      '/images/lamborghini/huracan-evo/Lamborghini-Huracan-Evo-front-600x400.jpg',
      '/images/lamborghini/huracan-evo/Lamborghini-Huracan-Evo-side-600x400.jpg',
      '/images/lamborghini/huracan-evo/Lamborghini-Huracan-Evo-rear-600x400.jpg',
      '/images/lamborghini/huracan-evo/Lamborghini-Huracan-Evo-interior-600x400.jpg',
      '/images/lamborghini/huracan-evo/Lamborghini-Huracan-Evo-engine-600x400.jpg',
    ],
    category: 'super',
    description: `The Lamborghini Huracan Evo is a supercar that combines the heart-pounding performance of a V10 engine with the latest in dynamic control systems. With 631 horsepower on tap, the Huracan Evo rockets from 0-60 mph in 2.9 seconds and hits a top speed of 202 mph. The advanced LDVI (Lamborghini Dinamica Veicolo Integrata) system adapts the car's behavior in real-time, ensuring optimal performance in all driving conditions. The luxurious cabin, cutting-edge technology, and aggressive design make the Huracan Evo a true icon in the world of supercars.`,
  },
  {
    id: 50,
    name: 'Aston Martin DB11',
    year: 2023,
    price: 2299,
    images: [
      '/images/aston-martin/db11/Aston-Martin-DB11-front-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-side-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-rear-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-interior-600x400.jpg',
      '/images/aston-martin/db11/Aston-Martin-DB11-engine-600x400.jpg',
    ],
    category: 'luxury',
    description: `The Aston Martin DB11 is a grand tourer that embodies British luxury and performance. Powered by a 5.2-liter twin-turbo V12 engine producing 630 horsepower, the DB11 accelerates from 0-60 mph in just 3.7 seconds and reaches a top speed of 208 mph. Its stunning design, meticulously crafted interior, and state-of-the-art technology make it a perfect blend of performance and refinement. Whether cruising along scenic routes or tackling high-speed highways, the DB11 delivers an unforgettable driving experience.`,
  }
];

export default cars;